---
vagrantfile-local:
    vm:
        box: ubuntu-precise12042-x64-vbox43
        box_url: 'http://box.puphpet.com/ubuntu-precise12042-x64-vbox43.box'
        hostname: null
        network:
            private_network: 192.168.111.222
            forwarded_port:
                mimHQ3ktS9Ic:
                    host: '8900'
                    guest: '22'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    memory: '1024'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            SO3qhcaXcVij:
                id: vagrant-root
                source: ./
                target: /var/www
                nfs: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages:
        - bzip2
        - wget
        - lsof
        - sudo
        - nano
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/bin
        log_path: /var/log/mailcatcher/mailcatcher.log
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - php
        - rewrite
    vhosts:
        0AKJV5gtPX8h:
            servername: app.dev
            serveraliases:
                - www.app.dev
            docroot: /var/www/source
            port: '80'
            setenv:
                - 'APP_ENV dev'
                - 'APP_ENV_SERVER vagrant'
            override:
                - All
            custom_fragment: ''
        7dsGhXFvUIYL:
            servername: applive.dev
            serveraliases:
                - www.applive.dev
            docroot: /var/www/dist
            port: '80'
            setenv:
                - 'APP_ENV product'
            override:
                - All
            custom_fragment: ''
        x0r2C7ZD4jRP:
            servername: applive.dev
            serveraliases:
                - www.applive.dev
            docroot: /var/www/dist
            port: '443'
            setenv:
                - 'APP_ENV product'
            override:
                - All
            custom_fragment: ''
    mod_pagespeed: 0
    mod_spdy: 0
php:
    install: '1'
    version: '53'
    composer: '1'
    modules:
        php:
            - cgi
            - cli
            - curl
            - gd
            - intl
            - mcrypt
            - memcache
        pear: {  }
        pecl:
            - APC
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: Europe/Berlin
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
        xdebug.remote_host: 192.168.111.222
        xdebug.idekey: PHPSTORM
        xdebug.profiler_enable: '0'
        xdebug.profiler_output_name: xdebug-profile.%R.%t
        xdebug.profiler_output_dir: /var/www/xdebug/profiles
        xdebug.profiler_enable_trigger: '1'
        xdebug.trace_output_dir: /var/www/xdebug/traces
        xdebug.trace_output_name: trace.%R.%t
drush:
    install: 0
    settings:
        drush.tag_branch: 6.x
mysql:
    install: '1'
    root_password: root
    phpmyadmin: '1'
    adminer: '1'
    databases:
        dBOWmgKTULTJ:
            grant:
                - ALL
            name: app
            host: localhost
            user: app
            password: app
            sql_file: ''
postgresql:
    install: 0
    root_password: '123'
    user_group: postgres
    databases: {  }
    adminer: 0
mariadb:
    install: 0
    root_password: '123'
    phpmyadmin: 0
    adminer: 0
    databases: {  }
    version: '10.0'
mongodb:
    install: '1'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: 0
    settings:
        conf_port: '6379'
beanstalkd:
    install: 0
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: 0
    settings:
        port: '5672'

